version: '3.8'

services:
  iris-app:
    image: iris-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./setosa.png:/app/setosa.png
      - ./versicolor.png:/app/versicolor.png
      - ./virginica.png:/app/virginica.png
    command: >
      /bin/bash -c "uvicorn FASTAPI:app --host 0.0.0.0 --port 8000 & streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0"
